# Setup
title:        BaseCubeOne
tagline:      A behaviour based smart home platform
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       openbase
  url:        http://openbase.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
